#jdbc
server:
  port: 8080
spring:
  mian:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:sqlite:D:/Software/IntelliJ/Project/Task Manager System/TaskManagerSystem/src/main/resources/static/task
    username: root
    password: password


mybatis:
  type-aliases-package: com.example.demo.pojo
